### ISSUE TITLE
Outdated npm readme

### ISSUE THREAD

**Issue by marklagendijk** [visurel/iconify-angular#12]
The documentation that is shown on the [package page on npm](https://www.npmjs.com/package/@visurel/iconify-angular) is outdated (it doesn't show the name syntax section).
The README.md in the latest published version is also outdated (which makes sense, because npm uses that).

Maybe you somehow locally had the outdated README when publishing the npm package?

**Comment by visurel** [comment]
There are 2 different README files, one is on the root of the project and the other is inside `/projects/iconify`. Looks like the PR we merged just included changes to the root README, but npm uses the `/projects/iconify` README. I'll update the other README to reflect the newest changes. Thanks for the hint. :v:
