### ISSUE TITLE
Import icon dynamically from module path

### ISSUE THREAD

**Issue by nguyenhmtriet** [visurel/iconify-angular#7]
Hi,
How can I show icon from icon module path? Because when importing dynamically it seems not to find that module.

Or maybe with a name icon, will I show it by not import static icon module path. Here is my code

```
const importIcon = '@iconify/icons-ic/' + item.icon;
const a = import(importIcon).then(icon => {
   console.log(icon);
});

```

ERROR Error: Uncaught (in promise): Error: Cannot find module '@iconify/icons-ic/twotone-layers'
Error: Cannot find module '@iconify/icons-ic/twotone-layers'

**Comment by visurel** [comment]
Looks like something related to the Angular Build system and not really to the library here.
